### ISSUE TITLE
Non-electronic selection prevent the use of Compilatio for other supported options

### ISSUE THREAD

**Issue by jfilliard** [sakaicontrib/compilatio-antiplagiarism#1]
When creating an assignment, the selection of "Non-electronic" value in the selection submission list, prevent the use of Compilatio for other supported options.

**Comment by mpellicer** [comment]
Is not a compilatio integration issue, it's a Sakai bug for all content review implementations.

Reported in this Jira:
https://jira.sakaiproject.org/browse/SAK-32117

Thanks @jfilliard for the information!
